// Generated by CoffeeScript 1.4.0
(function() {
  var Backbone, CollectionExposer, Select, SubscriptionMan2, SubscriptionMixin, Validator, callbackMsgEnd, collections, helpers, mongo, shared, v, _;

  Backbone = require('backbone4000');

  _ = require('underscore');

  helpers = require('helpers');

  Validator = require('validator2-extras');

  v = Validator.v;

  Select = Validator.Select;

  SubscriptionMan2 = require('./../subscriptionman2').SubscriptionMan2;

  collections = require('collections');

  mongo = require('collections/serverside/mongodb');

  shared = require('../shared');

  callbackMsgEnd = function(reply) {
    return function(err, data) {
      return reply.end({
        err: err,
        data: data
      });
    };
  };

  CollectionExposer = exports.CollectionExposer = Backbone.Model.extend4000({
    defaults: {
      name: void 0
    },
    initialize: function() {
      var lweb, name,
        _this = this;
      name = this.get('name');
      lweb = this.get('lweb');
      lweb.subscribe({
        collection: name,
        create: true
      }, function(msg, reply) {
        return _this.create(msg.create, callbackMsgEnd(reply));
      });
      lweb.subscribe({
        collection: name,
        remove: true,
        raw: true
      }, function(msg, reply) {
        return _this.remove(msg.remove, callbackMsgEnd(reply));
      });
      lweb.subscribe({
        collection: name,
        remove: true
      }, function(msg, reply) {
        return _this.findModels(msg.remove, {}, function(entry) {
          if (entry != null) {
            return entry.remove();
          } else {
            return reply.end();
          }
        });
      });
      lweb.subscribe({
        collection: name,
        update: true,
        data: true
      }, function(msg, reply) {
        var counter;
        console.log("collection got update request", msg);
        counter = 0;
        return _this.findModels(msg.update, {}, function(entry) {
          if (!entry) {
            return reply.end({
              updated: counter
            });
          }
          entry.update(msg.data);
          entry.flush(function() {
            return true;
          });
          return counter++;
        });
      });
      lweb.subscribe({
        collection: name,
        find: true
      }, function(msg, reply) {
        return _this.find(msg.find, msg.limits || {}, function(entry) {
          if (entry != null) {
            return reply.write({
              data: entry,
              err: void 0
            });
          } else {
            return reply.end();
          }
        });
      });
      lweb.subscribe({
        collection: name,
        findOne: true
      }, function(msg, reply) {
        return _this.findOne(msg.findOne, function(err, entry) {
          if (entry != null) {
            return reply.end({
              data: entry,
              err: void 0
            });
          } else {
            return reply.end();
          }
        });
      });
      return lweb.subscribe({
        collection: name,
        call: true,
        data: true
      }, function(msg, reply, realm) {
        return _this.fcall(msg.call, msg.args || [], msg.data, realm, function(err, data) {
          return reply.end({
            err: err,
            data: data
          });
        });
      });
    },
    subscribeModel: function(id, callback) {
      return this.get('lweb').channel(id).subscribe(true, function(msg) {
        return callback(msg);
      });
    }
  });

  SubscriptionMixin = exports.SubscriptionMixin = shared.SubscriptionMan2.extend4000({
    superValidator: v({
      create: 'function',
      update: 'function',
      remove: 'function'
    }),
    create: function(entry, callback) {
      var _this = this;
      return this._super('create', entry, function(err, id) {
        _this.event({
          action: 'create',
          entry: _.extend({
            id: id
          }, entry)
        });
        return callback(err, id);
      });
    },
    update: function(pattern, update, callback) {
      this._super('update', pattern, update, callback);
      if (pattern.id) {
        return this.event({
          action: 'update',
          id: pattern.id,
          update: update
        });
      }
    },
    remove: function(pattern, callback) {
      this._super('remove', pattern, callback);
      if (pattern.id) {
        return this.event({
          action: 'remove',
          id: pattern.id
        });
      }
    },
    subscribeModel: function(id, callback) {
      return this.subscribe({
        pattern: {
          id: id
        }
      }, function(msg) {
        return callback(msg);
      });
    },
    unsubscribeModel: function() {
      return true;
    }
  });

  exports.MongoCollection = mongo.MongoCollection.extend4000(CollectionExposer, collections.ReferenceMixin, collections.ModelMixin, exports.SubscriptionMixin);

}).call(this);
