// Generated by CoffeeScript 1.4.0
(function() {
  var connect, io;

  io = require('socket.io-browserify');

  connect = exports.connect = function(host) {
    if (host == null) {
      host = "http://" + window.location.host;
    }
    return true;
  };

}).call(this);
