// Generated by CoffeeScript 1.4.0
(function() {
  var Backbone, SubscriptionMan;

  Backbone = require('backbone4000');

  SubscriptionMan = require('subscriptionman').SubscriptionMan;

  exports.common = 'hi there';

  exports.QueryNode = SubscriptionMan.extend4000({
    initialize: function() {
      return true;
    }
  });

}).call(this);
