// Generated by CoffeeScript 1.7.1
(function() {
  var backbone, conversationMan, streamingProtocol, subscriptionMan2;

  backbone = require('backbone4000');

  subscriptionMan2 = require('subscriptionman2');

  streamingProtocol = backbone.Model.extend4000({
    send: function(data) {
      return true;
    },
    receive: function(callback) {
      return callback('msg', 'realm');
    }
  });

  conversationMan = subscriptionMan2.extend4000({
    query: function(msg) {}
  });

}).call(this);
