// Generated by CoffeeScript 1.4.0
(function() {
  var SimpleMatcher, SubscriptionMan2,
    __slice = [].slice;

  SimpleMatcher = Backbone.Model.extend4000({
    match: function(value, pattern) {
      if (pattern === true) {
        return true;
      }
      return !_.find(pattern, function(checkvalue, key) {
        if (!value[key]) {
          return true;
        }
        if (checkvalue !== true && value[key] !== checkvalue) {
          return true;
        }
        return false;
      });
    }
  });

  SubscriptionMan2 = exports.SubscriptionMan2 = SimpleMatcher.extend4000({
    initialize: function() {
      return this.subscriptions = [];
    },
    subscribe: function(pattern, callback, name) {
      if (!callback && pattern.constructor === Function) {
        callback = pattern;
        pattern = true;
      }
      return this.subscriptions.push({
        pattern: pattern,
        callback: callback
      });
    },
    event: function() {
      var subscriptions, value, values,
        _this = this;
      values = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      value = _.first(values);
      subscriptions = _.filter(this.subscriptions, function(subscription) {
        return _this.match(value, subscription.pattern);
      });
      return _.map(subscriptions, function(subscription) {
        return subscription.callback.apply(this, values);
      });
    }
  });

}).call(this);
