// Generated by CoffeeScript 1.4.0
(function() {
  var lwebc, lwebs;

  lwebs = require('./serverside');

  lwebc = require('./clientisde');

  exports.basic = function(test) {
    lwebs = lwebs.listen();
    lwebc = lwebc.connect();
    lwebc.channels.on('channel1', function(msg) {
      return console.log('channel msg', msg);
    });
    lwebs.channels.broadcast('channel1', {
      message: 'test message1'
    });
    lwebs.on({
      bla: true
    }, function(msg, response, client) {
      response.send({
        response: 1
      });
      return response.end({
        response: 2
      });
    });
    lwebc.query({
      bla: 3
    }, function(err, msg) {
      return console.log('got', msg);
    });
    return lwebc.multiQuery({
      bla: 3
    }, function(err, data) {
      return true;
    });
  };

}).call(this);
